#!/usr/bin/env bash

#
# Public: mk_cache() function for grav-mkcache.sh script.
#
function libgrav_mk::mk_cache() { # Public: mk_cache() function for grav-mkcache.sh script.
   local _RC=0
   local _GRAV_NAME="${1}"
   local _GRAV_CACHE="${2}"
 
   sudo docker volume create \
      --driver local \
      --opt type=none \
      --opt device="${_GRAV_CACHE}" \
      --opt o=bind "${_GRAV_NAME}" 1>/dev/stderr 1>/dev/null 2>&1
   
   mkdir -p "${_GRAV_CACHE}"/.ccache
   mkdir -p "${_GRAV_CACHE}"/.phpcache
   echo "GRAV_CACHE=${_GRAV_CACHE}" > ${CFG_DIR}/.config.cache
   

   libgrav::help "INFO: Created cached directory '${_GRAV_NAME}' in ${_GRAV_CACHE}."

   _RC=$?

   return ${_RC}
}

#
# Public: mk_data() function for grav-mkdata.sh script.
#
function libgrav_mk::mk_data() { # Public: mk_data() function for grav-mkdata.sh script.
   local _RC=0
   local _GRAV_NAME="${1}"
   local _GRAV_DATA="${2}"
 
   sudo docker volume create \
      --driver local \
      --opt type=none \
      --opt device="${_GRAV_DATA}" \
      --opt o=bind "${_GRAV_NAME}" 1>/dev/null 2>&1
   
   if [[ -e "${_GRAV_DATA}/.gitkeep" ]]; then rm -f "${_GRAV_DATA}/.gitkeep"; fi
   if [[ ! -e "${_GRAV_DATA}" ]]; then mkdir -p ${_GRAV_DATA}; fi

   echo "GRAV_DATA=${_GRAV_DATA}" > ${CFG_DIR}/.config.data
   
   libgrav::help "INFO: Created data directory '${_GRAV_NAME}' in ${_GRAV_DATA}."

   _RC=$?

   return ${_RC}
}

#
# Public: mk_init() function for grav-mkinit.sh script.
#
function libgrav_mk::mk_init() { # Public: mk_init() function for grav-mkinit.sh script.
   local _RC=0
   local _GRAV_CMD="${1}"
   local _GRAV_HOME="${2}" 
   local _GRAV_ROOT="${3}" 
   local _GRAV_CACHE="${4}" 
   local _GRAV_DATA="${5}" 
   local _GRAV_DOCK="${6}" 
   local _GRAV_BIN="${7}" 
   local _GRAV_CFG="${8}" 
   local _GRAV_KEY="${9}" 
   local _GRAV_LIB="${10}"

   # Minimal requirements
   local _DOCKER_MIN="20.10"
   local _BUILDX_MIN="0.5.0"
   local _JQ_MIN="1.5"
   local _OPENSSL_MIN="1.1.1"

   local _DOCKER_NOW="$(docker info --format '{{json .ServerVersion}}' | tr -d '"')"
   local _BUILDX_NOW="$(docker info --format '{{json .ClientInfo}}' | jq -r '.Plugins[] | select(.Name | contains("buildx")) | .Version ' | cut -d'v' -f2)"
   local _JQ_NOW="$(jq --version | cut -d'-' -f2)"
   local _OPENSSL_NOW="$(openssl version|  awk '{print $2}' | tr -dc '0-9.')"

   # Do not check only important for multi architecture detection
   local _DISTRO_NOW="$(cat /etc/*release 2>/dev/null | grep -w ID | cut -d'=' -f2)"

   case "${_GRAV_CMD}" in
      init)
         # Check all required minimal versions
         if [ $(libgrav::version "${_DOCKER_NOW}") -lt $(libgrav::version ${_DOCKER_MIN}) ]; then 
            libgrav::error 2 "FAIL: Required version of docker is not available or met.\nPlease install at least required version: ${_DOCKER_MIN}."
         elif [ $(libgrav::version "${_BUILDX_NOW}") -lt $(libgrav::version ${_BUILDX_MIN}) ]; then 
            libgrav::error 2 "FAIL: Required version of docker buildx plugin is not available or met.\nPlease install at least required version: (${_BUILDX_MIN}."
         elif [ $(libgrav::version "${_JQ_NOW}") -lt $(libgrav::version ${_JQ_MIN}) ]; then 
            libgrav::error 2 "FAIL: Required version of jq is not available or met.\nPlease install at least required version: ${_JQ_MIN}."
         elif [ $(libgrav::version "${_OPENSSL_NOW}") -lt $(libgrav::version ${_OPENSSL_MIN}) ]; then 
            libgrav::error 2 "FAIL: Required version of openssl is not available or met.\nPlease install at least required version: ${_OPENSSL_MIN}."
         fi

         # Set global directory variables
         echo "GRAV_HOME=\"${_GRAV_HOME}\"" > "${_GRAV_CFG}"/.config.home 
         echo "GRAV_ROOT=\"${_GRAV_ROOT}\"" > "${_GRAV_CFG}"/.config.root 
         #echo "GRAV_CACHE=\"${_GRAV_CACHE}\"" > "${_GRAV_CFG}"/.config.cache
         #echo "GRAV_DATA=\"${_GRAV_DATA}\"" > "${_GRAV_CFG}"/.config.data
         echo "GRAV_DOCK=\"${_GRAV_DOCK}\"" > "${_GRAV_CFG}"/.config.docker
         echo "GRAV_BIN=\"${_GRAV_BIN}\"" > "${_GRAV_CFG}"/.config.bin 
         echo "GRAV_CFG=\"${_GRAV_CFG}\"" > "${_GRAV_CFG}"/.config.cfg
         echo "GRAV_KEY=\"${_GRAV_KEY}\"" > "${_GRAV_CFG}"/.config.key
         echo "GRAV_LIB=\"${_GRAV_LIB}\"" > "${_GRAV_CFG}"/.config.lib 
         echo "GRAV_CTX=\"${_GRAV_CFG}\"" > "${_GRAV_HOME}"/.context

         # Replace '# docker-grav #' entries in .bashrc file
         if [[ -e "${HOME}/.bashrc" ]] && [ "${SHELL}" == "/bin/bash" ]; then 
            sed -i "/# docker-grav #/d" ${HOME}/.bashrc
            echo "export PATH=${PWD}/bin:\${PATH} # docker-grav #" >> ${HOME}/.bashrc
            echo "export GRAV_HOME=${_GRAV_HOME} # docker-grav #" >>  ${HOME}/.bashrc
         fi

         if [[ ! -e "${HOME}/.bash_aliases" ]] && [ "${SHELL}" == "/bin/bash" ]; then 
            touch ${HOME}/.bash_aliases
         else
            sed -i "/# docker-grav #/d" ${HOME}/.bash_aliases
         fi

         echo 'alias "grav-build"="grav-build.sh" # docker-grav #' >> ${HOME}/.bash_aliases
         echo 'alias "grav-getcore"="grav-getcore.sh" # docker-grav #' >> ${HOME}/.bash_aliases
         echo 'alias "grav-mkcache"="grav-mkcache.sh" # docker-grav #' >> ${HOME}/.bash_aliases
         echo 'alias "grav-mkdata"="grav-mkdata.sh" # docker-grav #' >> ${HOME}/.bash_aliases
         echo 'alias "grav-mkinit"="grav-mkinit.sh" # docker-grav #' >> ${HOME}/.bash_aliases
         echo 'alias "grav-mkpass"="grav-mkpass.sh" # docker-grav #' >> ${HOME}/.bash_aliases
         echo 'alias "grav-mkssh"="grav-mkssh.sh" # docker-grav #' >> ${HOME}/.bash_aliases
         echo 'alias "grav-purge"="grav-purge.sh" # docker-grav #' >> ${HOME}/.bash_aliases
         echo 'alias "grav-run"="grav-run.sh" # docker-grav #' >> ${HOME}/.bash_aliases
         echo 'alias "grav-setcore"="grav-setcore.sh" # docker-grav #' >> ${HOME}/.bash_aliases
         echo 'alias "grav-shell"="grav-shell.sh" # docker-grav #' >> ${HOME}/.bash_aliases

         # Set current grav core version strings
         # "${BIN_DIR}"/grav-setcore.sh prod
         # "${BIN_DIR}"/grav-setcore.sh dev
      ;;
      
      
      *) libgrav::error 2 "FAIL: Argument is not defined: ${_GRAV_CMD}!"
      ;;

   esac

   return ${_RC}
}

#
# Public: mk_pass() function for grav-mkpass.sh script.
#
function libgrav_mk::mk_pass() { # Public: mk_pass() function for grav-mkpass.sh script.
   local _RC=0
   local _GRAV_SECS="${1}"
   local _GRAV_USER="${2}"
   local _GRAV_PASS="${3}"
   local _GRAV_PW=""

   _GRAV_PW="$(openssl passwd -6 -salt $(openssl rand -base64 32) ${_GRAV_SECS})"
   
   _RC=$?

   if [[ -f "${_GRAV_PASS}" ]]; then chmod 600 "${_GRAV_PASS}"; fi

   echo ${_GRAV_USER}:${_GRAV_PW} > "${_GRAV_PASS}"
   _RC=$?
   
   chmod 400 "${_GRAV_PASS}"

   echo "GRAV_USER=${_GRAV_USER}" > "${CFG_DIR}"/.config.user
   echo "GRAV_PASS=${_GRAV_PASS}" > "${CFG_DIR}"/.config.pass
   
   libgrav::help "INFO: Created encrypted password for user '${_GRAV_USER}' in ${KEY_DIR} directory."

   return ${_RC}
}

#
# Public: mk_ssh() function for grav-mkssh.sh script.
#
function libgrav_mk::mk_ssh() { # Public: mk_ssh() function for grav-mkssh.sh script.
   local _RC=0
   local _GRAV_EMAIL="${1}"
   local _GRAV_TYPE="${2}"
   local _GRAV_LENGTH="${3}"
   local _GRAV_SSH="${4}"

   local _GRAV_CHOICE=""
   local _GRAV_ANSWER=""
   local _GRAV_VERB=""
   local _GRAV_VERB1="Created"
   local _GRAV_VERB2="Used own"
   local _GRAV_VERB3="Reused"

   if [[ -e "${_GRAV_SSH}" ]] && [[ -e "${_GRAV_SSH}.pub" ]]; then
      _GRAV_CHOICE=3
      _GRAV_ANSWER=$(libgrav::multi_choice ${_GRAV_CHOICE} "${_GRAV_SSH} already exists.
(1) Overwrite, (2) Use own, (3) Reuse it ")
   else
      _GRAV_CHOICE=2
      _GRAV_ANSWER=$(libgrav::multi_choice ${_GRAV_CHOICE} "${_GRAV_SSH} already exists.
(1) Create, (2) Use own ")
   fi
   while true; do
      case "${_GRAV_ANSWER}" in
         1) 
            if [ ${_GRAV_CHOICE} -eq 2 ]; then _GRAV_VERB="${_GRAV_VERB1}"; else _GRAV_VERB="${_GRAV_VERB1} new"; fi
            if [[ -e "${_GRAV_SSH}" ]]; then rm -f ${_GRAV_SSH}; fi
            if [[ -e "${_GRAV_SSH}".pub ]]; then rm -f ${_GRAV_SSH}.pub; fi
            ssh-keygen -q -C "${_GRAV_EMAIL}" -t ${_GRAV_TYPE} -b ${_GRAV_LENGTH} -f "${_GRAV_SSH}" -N ''
            break;
         ;;

         2) 
            _GRAV_VERB="${_GRAV_VERB2}"
            if [[ -e "${_GRAV_SSH}" ]]; then rm -f ${_GRAV_SSH}; fi
            if [[ -e "${_GRAV_SSH}".pub ]]; then rm -f ${_GRAV_SSH}.pub; fi
            cp $HOME/.ssh/id_rsa ${KEY_DIR}/grav_rsa
            cp $HOME/.ssh/id_rsa.pub ${KEY_DIR}/grav_rsa.pub
            break;
         ;;

         3) 
            _GRAV_VERB="${_GRAV_VERB3}"
            break
         ;;
      esac
   done

   echo "GRAV_SSH=${_GRAV_SSH}" > ${CFG_DIR}/.config.ssh

   libgrav::help "INFO: ${_GRAV_VERB} SSH keys in ${KEY_DIR} directory."

   _RC=$?

   return ${_RC}
}
