#!/usr/bin/env bash

#
# Public: get_core() function for grav-getcore.sh script.
#
function libgrav_get::get_core() { # Public: get_core() function for grav-getcore.sh script.
   local _RC=0
   local _GRAV_CORE="${1}"
   local _GRAV_NAME="${2}"
   local _GRAV_KIND="${3}"

   local _GRAV_URL=""
   local _GRAV_DEV=""
   local _GRAV_PROD=""
   local _GRAV_OUTPUT=""
   local _GRAV_URL="https://getgrav.org/download"

   case "${_GRAV_CORE}" in
      all)
         ${0} dev ${_GRAV_NAME}
         ${0} prod ${_GRAV_NAME}
      ;;

      dev)
         _GRAV_DEV=$(cat "${CFG_DIR}"/.config.dev | tr -d '"' | cut -d'=' -f2)
         _GRAV_OUTPUT="${ROOT_DIR}/tmp/grav/core/${_GRAV_NAME}-${_GRAV_DEV}?testing.zip"
         if [[ -e "${_GRAV_OUTPUT}" ]]; then libgrav::error 2 "Error: File ${_GRAV_OUTPUT} exists, download not needed."; fi

         wget -O "${_GRAV_OUTPUT}" \
            ${_GRAV_URL}/${_GRAV_KIND}/${_GRAV_NAME}/${_GRAV_DEV}?testing
      ;;

      [0-9]*.[0-9]*.[0-9]*-[a-z][a-z].[0-9]*)
         _GRAV_OUTPUT="${ROOT_DIR}/tmp/grav/core/${_GRAV_NAME}-${_GRAV_CORE}?testing.zip"
         if [[ -e "${_GRAV_OUTPUT}" ]]; then libgrav::error 2 "Error: File ${_GRAV_OUTPUT} exists, download not needed."; fi

         wget -O "${_GRAV_OUTPUT}" \
            ${_GRAV_URL}/${_GRAV_KIND}/${_GRAV_NAME}/${_GRAV_CORE}?testing
      ;;

      prod)
         _GRAV_PROD=$(cat "${CFG_DIR}"/.config.prod | tr -d '"' | cut -d'=' -f2)
         _GRAV_OUTPUT="${ROOT_DIR}/tmp/grav/core/${_GRAV_NAME}-${_GRAV_PROD}.zip"
         if [[ -e "${_GRAV_OUTPUT}" ]]; then libgrav::error 2 "Error: File ${_GRAV_OUTPUT} exists, download not needed."; fi

         wget -O "${_GRAV_OUTPUT}" \
            ${_GRAV_URL}/${_GRAV_KIND}/${_GRAV_NAME}/${_GRAV_PROD}
      ;;
      
      [0-9]*.[0-9]*.[0-9]*)
         _GRAV_OUTPUT="${ROOT_DIR}/tmp/grav/core/${_GRAV_NAME}-${_GRAV_CORE}.zip"
         if [[ -e "${_GRAV_OUTPUT}" ]]; then libgrav::error 2 "Error: File ${_GRAV_OUTPUT} exists, download not needed."; fi

         wget -O "${_GRAV_OUTPUT}" \
            ${_GRAV_URL}/${_GRAV_KIND}/${_GRAV_NAME}/${_GRAV_CORE}
      ;;

      *) libgrav::error 2 "Error: Argument is not defined: ${_GRAV_CORE}!"
      ;;

   esac

   return ${_RC}
}
