#!/usr/bin/env bash

#
# Public: mk_init() function for grav-mkinit.sh script.
#
function libgrav_init::mk_init() { #-# Public: mk_init() function for grav-mkinit.sh script.
   local _RC=0
   local _GRAV_CMD="${1}"

   # Prerequisite checking
   local _UUID_MIN="${2}"
   local _DOCKER_MIN="${3}"
   local _BUILDX_MIN="${4}"
   local _JQ_MIN="${5}"
   local _OPENSSL_MIN="${6}"
   local _GIT_MIN="${7}"
   local _GETSSL_MIN="${8}"
   local _WGET_MIN="${9}"

   # Initialize directories
   if [[ ! -d "${CFG_DIR}" ]]; then mkdir -p "${CFG_DIR}"; fi
   if [[ ! -d "${KEY_DIR}" ]]; then mkdir -p "${KEY_DIR}"; fi
   if [[ ! -d "${ROOT_DIR}" ]]; then mkdir -p "${ROOT_DIR}"; fi
         
   libgrav_common::check_prereq \
      "${_UUID_MIN}" \
      "${_DOCKER_MIN}" \
      "${_BUILDX_MIN}" \
      "${_JQ_MIN}" \
      "${_OPENSSL_MIN}" \
      "${_GIT_MIN}" \
      "${_GETSSL_MIN}" \
      "${_WGET_MIN}"

   case "${_GRAV_CMD}" in
      init)
         # Set global directory variables
         echo "GRAV_HOME=\"${HOME_DIR}\"" > "${CFG_DIR}"/.config.home 
         echo "GRAV_ROOT=\"${ROOT_DIR}\"" > "${CFG_DIR}"/.config.root 
         echo "GRAV_DOCK=\"${DOCK_DIR}\"" > "${CFG_DIR}"/.config.docker
         echo "GRAV_BIN=\"${BIN_DIR}\"" > "${CFG_DIR}"/.config.bin 
         echo "GRAV_CFG=\"${CFG_DIR}\"" > "${CFG_DIR}"/.config.cfg
         echo "GRAV_KEY=\"${KEY_DIR}\"" > "${CFG_DIR}"/.config.key
         echo "GRAV_LIB=\"${LIB_DIR}\"" > "${CFG_DIR}"/.config.lib 
         echo "GRAV_CTX=\"${CFG_DIR}\"" > "${HOME_DIR}"/.context

         # Replace '# docker-grav #' entries in .bashrc file
         if [[ -e "${HOME}/.bashrc" ]] && [ "${SHELL}" == "/bin/bash" ]; then 
               if [ "${OSTYPE:0:6}" == "darwin" ]; then
                  sed -i "" "/# docker-grav #/d" "${HOME}"/.bashrc
               else   
                  sed -i "/# docker-grav #/d" "${HOME}"/.bashrc
               fi
            echo "export GRAV_HOME="${HOME_DIR}" # docker-grav #" >>  "${HOME}"/.bashrc
            echo "export GRAV_ROOT="\${GRAV_HOME}/rootfs" # docker-grav #" >>  "${HOME}"/.bashrc
            echo "export GRAV_DOCK="\${GRAV_HOME}/docker" # docker-grav #" >>  "${HOME}"/.bashrc
            echo "export GRAV_CACHE="\${GRAV_HOME}/cache" # docker-grav #" >>  "${HOME}"/.bashrc
            echo "export GRAV_CERT="\${GRAV_HOME}/cert" # docker-grav #" >>  "${HOME}"/.bashrc
            echo "export GRAV_DATA="\${GRAV_HOME}/data" # docker-grav #" >>  "${HOME}"/.bashrc
            echo "export GRAV_BIN="\${GRAV_HOME}/bin" # docker-grav #" >>  "${HOME}"/.bashrc
            echo "export GRAV_CFG="\${GRAV_HOME}/cfg" # docker-grav #" >>  "${HOME}"/.bashrc
            echo "export GRAV_KEY="\${GRAV_HOME}/key" # docker-grav #" >>  "${HOME}"/.bashrc
            echo "export GRAV_LIB="\${GRAV_HOME}/lib" # docker-grav #" >>  "${HOME}"/.bashrc
            echo "export PATH=\${GRAV_HOME}/bin:\${PATH} # docker-grav #" >> "${HOME}"/.bashrc
            if [ "${OSTYPE:0:6}" == "darwin" ]; then
               echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> "${HOME}"/.bashrc
            fi
         fi

         if [ "${SHELL}" == "/bin/bash" ]; then
            if [[ ! -e "${HOME}/.bash_aliases" ]]; then 
               touch ${HOME}/.bash_aliases;
            else
               if [ "${OSTYPE:0:6}" == "darwin" ]; then
                  sed -i "" "/# docker-grav #/d" ${HOME}/.bash_aliases;
               else
                  sed -i "/# docker-grav #/d" ${HOME}/.bash_aliases;
               fi
            fi
         fi

         echo 'alias "grav-build"="grav-build.sh" # docker-grav #' >> "${HOME}"/.bash_aliases
         echo 'alias "grav-core"="grav-core.sh" # docker-grav #' >> "${HOME}"/.bash_aliases
         echo 'alias "grav-mkcache"="grav-mkcache.sh" # docker-grav #' >> "${HOME}"/.bash_aliases
         echo 'alias "grav-mkdata"="grav-mkdata.sh" # docker-grav #' >> "${HOME}"/.bash_aliases
         echo 'alias "grav-mkcert"="grav-mkcert.sh" # docker-grav #' >> "${HOME}"/.bash_aliases
         echo 'alias "grav-mkinit"="grav-mkinit.sh" # docker-grav #' >> "${HOME}"/.bash_aliases
         echo 'alias "grav-mkpass"="grav-mkpass.sh" # docker-grav #' >> "${HOME}"/.bash_aliases
         echo 'alias "grav-mkssh"="grav-mkssh.sh" # docker-grav #' >> "${HOME}"/.bash_aliases
         echo 'alias "grav-purge"="grav-purge.sh" # docker-grav #' >> "${HOME}"/.bash_aliases
         echo 'alias "grav-run"="grav-run.sh" # docker-grav #' >> "${HOME}"/.bash_aliases
         echo 'alias "grav-shell"="grav-shell.sh" # docker-grav #' >> "${HOME}"/.bash_aliases
         echo 'function grav-cd() { cd ${GRAV_HOME}/"${1}"; } #-# # docker-grav #' >> "${HOME}"/.bash_aliases
         echo 'function func() { cd ${GRAV_LIB}; ls -c ${1:-"."} | xargs -r cat | grep "#-#"; } #-# # docker-grav #' >> "${HOME}"/.bash_aliases
      ;;
      
      
      *) libgrav_common::error 2 "Error: Argument is not defined: ${_GRAV_CMD}!" "${NAME}"
      ;;

   esac

   return ${_RC}
}
