#!/usr/bin/env bash

#
# usage function for all shell scripts
#
usage() {
   local _RC=${1}
   local _TEXT="${2}"
   local _ARGS="${3:-""}"
   local _NOTE="${4:-""}"
   local _INFO="${5:-""}"
   local _ARG1="${6:-""}"
   local _ARG2="${7:-""}"
   local _ARG3="${8:-""}"
   local _ARG4="${9:-""}"
   local _ARG5="${10:-""}"
   local _ARG6="${11:-""}"
   local _ARG7="${12:-""}"

   case ${_RC}  in
      1)
         echo ${_TEXT}
         echo ""
         echo "${_ARGS}"
         echo "${_NOTE}"
         echo ""
         test ! -z "${_ARG1}" && echo "${_ARG1}"
         test ! -z "${_ARG2}" && echo "${_ARG2}"
         test ! -z "${_ARG3}" && echo "${_ARG3}"
         test ! -z "${_ARG4}" && echo "${_ARG4}"
         test ! -z "${_ARG5}" && echo "${_ARG5}"
         test ! -z "${_ARG6}" && echo "${_ARG6}"
         test ! -z "${_ARG7}" && echo "${_ARG7}"
         echo ""
         echo "${_INFO}"
      ;;

      *)
         echo ""
         echo ${_TEXT}
      ;;
   
   esac
   
   exit ${_RC}
}
