#!/usr/bin/env bash
#
#
#
init() {
   # Remove enclosing double quotes
   ROOT_DIR="$(cat ${CTX_DIR}/.config.root | tr -d '"' | cut -d'=' -f2)"
   CACHE_DIR="$(cat ${CTX_DIR}/.config.cache | tr -d '"' | cut -d'=' -f2)"
   DATA_DIR="$(cat ${CTX_DIR}/.config.data | tr -d '"' | cut -d'=' -f2)"
   DOCK_DIR="$(cat ${CTX_DIR}/.config.docker | tr -d '"' | cut -d'=' -f2)"
   BIN_DIR="$(cat ${CTX_DIR}/.config.bin | tr -d '"' | cut -d'=' -f2)"
   CFG_DIR="$(cat ${CTX_DIR}/.config.cfg | tr -d '"' | cut -d'=' -f2)"
   KEY_DIR="$(cat ${CTX_DIR}/.config.key | tr -d '"' | cut -d'=' -f2)"
}

#
# help function for all shell scripts
#
help() {
   local _HELP="${1}"
   
   echo ""
   echo -e "${_HELP}"
   echo ""
}

#
# usage function for all shell scripts
#
usage() {
   local _RC=${1}
   local _TEXT="${2}"
   local _ARGS="${3:-""}"
   local _NOTE="${4:-""}"
   local _INFO="${5:-""}"
   local _HELP="${6:-""}"
   local _ARG1="${7:-""}"
   local _ARG2="${8:-""}"
   local _ARG3="${9:-""}"
   local _ARG4="${10:-""}"
   local _ARG5="${11:-""}"
   local _ARG6="${12:-""}"
   local _ARG7="${13:-""}"

   case ${_RC}  in
      1)
         echo "${_TEXT}"
         echo ""
         echo "${_ARGS}"
         echo "${_NOTE}"
         echo ""
         test ! -z "${_ARG1}" && echo "${_ARG1}"
         test ! -z "${_ARG2}" && echo "${_ARG2}"
         test ! -z "${_ARG3}" && echo "${_ARG3}"
         test ! -z "${_ARG4}" && echo "${_ARG4}"
         test ! -z "${_ARG5}" && echo "${_ARG5}"
         test ! -z "${_ARG6}" && echo "${_ARG6}"
         test ! -z "${_ARG7}" && echo "${_ARG7}"
         echo ""
         echo "${_INFO}"
         help "${_HELP}"
      ;;

      *)
         echo ""
         echo ${_TEXT}
      ;;
   
   esac
   
   exit ${_RC}
}

#
# error function for all shell scripts
#
error() {
   local _RC=${1}
   local _TEXT="${2}"

   case ${_RC}  in
      *)
         echo ""
         echo ${_TEXT}
      ;;
   
   esac
   
   exit ${_RC}
}
