#!/usr/bin/env bash

#
# Setcore function for grav_setcore.sh script
#
setcore() {
   local _RC=0
   local _GRAV_CORE="${1}"

   case "${_GRAV_CORE}" in
      prod) echo "GRAV_PROD=$(wget -O - -o /dev/null https://getgrav.org | grep 'Stable Version' | sed -e 's/<[^>]*>//g' | awk '{print $3}')"  > "${PWD}"/.context.prod 
      ;;
      
      [0-9]*.[0-9]*.[0-9]*)
         echo "GRAV_PROD=${_GRAV_CORE}"  > "${PWD}"/.context.prod 
      ;;

      dev) echo "GRAV_DEV=$(wget -O - -o /dev/null https://getgrav.org |grep 'Release Candidate Version' | sed -e 's/<[^>]*>//g' | awk '{print $4}')" > "${PWD}"/.context.dev 
      ;;
          
      [0-9]*.[0-9]*.[0-9]*-[a-z][a-z].[0-9]*\?testing)
         echo "GRAV_DEV=${_GRAV_CORE}"  > "${PWD}"/.context.dev 
      ;;

      *) error 2 "FAIL: Argument is not defined: ${_GRAV_CORE}!"
      ;;

   esac

   return ${_RC}
}

